name: trackify
description: "A Flutter habit-tracking application built as a learning project during the 100 Days of Code challenge."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  dynamic_color: ^1.8.1
  file_picker: ^12.0.0-beta.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  http: ^1.6.0
  package_info_plus: ^10.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5  # Used for storing simple key-value pairs locally on the device
  table_calendar: ^3.2.0
  timezone: ^0.11.0
  url_launcher: ^6.3.2
  uuid: ^4.5.3                # Used for generating unique identifiers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  # Custom Themes:
  # assets:
  #   - assets/custom_theme.json

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon.png"
#   min_sdk_android: 21 
#   web:
#     generate: true
#     image_path: "assets/icon.png"
#   windows:
#     generate: true
#     image_path: "assets/icon.png"
#   macos:
#     generate: true
#     image_path: "assets/icon.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  
  # Android Adaptive Icon settings (Injects the #e3e3e3 background)
  adaptive_icon_background: "#e3e3e3"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21
  
  # iOS settings (Forces the background color since iOS blocks transparency)
  remove_alpha_ios: true
  background_color_ios: "#e3e3e3"
  
  # Web PWA config
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#e3e3e3"
    theme_color: "#e3e3e3"
    
  # Desktop config
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"